### ISSUE TITLE
Frequency causes crash and world no longer loads without crashing

### ISSUE THREAD

**Issue by Syndrick** [ACCBDD/simplevoicechat-radio#3]
I was testing your mod, and changed the frequency of the radio, and it crashed my game. Now when I try to load that world it gives me the same crash, saying "Exception caught during firing event:  does not follow frequency pattern!"

Here's the latest log for the crash when trying to load said world (Google drive link and uploading the file directly, idk which works better so here's both):

https://drive.google.com/file/d/1xwyEXOY__CRHfhzppwWK8b2jPdM224GT/view?usp=sharing 

[latest.log](https://github.com/ACCBDD/simplevoicechat-radio/files/14075462/latest.log)

**Comment by ACCBDD** [comment]
It looks like there might be some kind of conflict with ModernFix - does removing that mod from your game stop the crashes from happening? Additionally, is this on the server side or the client side?

**Comment by Syndrick** [comment]
This is client side. I disabled ModernFix and still got the same crash.

[latest.log](https://github.com/ACCBDD/simplevoicechat-radio/files/14075500/latest.log)

**Comment by Syndrick** [comment]
I wouldn't be surprised if it's just an incompatibility with some of the other mods, since I have quite a few that make some big changes to the way the game runs. But, I thought I might as well bring it up to you just incase it is a bug

**Comment by ACCBDD** [comment]
No problem! Can you try recreating this bug in another world? From the stacktrace, it's telling me that you are trying to pick up a radio with no frequency assigned, which should basically never happen - I'm trying to recreate this in my debug environment to get to the bottom of this.

**Comment by Syndrick** [comment]
Okay, so I recreated the exact steps as the first time, and no crash so far. Basically, all I did was I had 2 radios, and changed the frequency of 1, and dropped it, and then used the other one, and then went to pick up the one I dropped, and then the crash happened. 

I did that same thing on a new world, and no crash. So maybe it was a weird fluke? Thankfully the world that won't load was a creative test world

**Comment by ACCBDD** [comment]
I've found the answer! If you throw a crafted or spawned in radio into the world without grabbing it first, it crashes your game due to some logic I put in. I've fixed this in version 1.4.0.1, currently in the process of being approved on CurseForge.

Thank you for bringing this issue up!

**Comment by Syndrick** [comment]
Awesome, I'm glad I was able to help. I'm super excited to used this mod with my friends, so it's awesome that there was a fix for this. Thank you, and keep up the great work my friend!
