### ISSUE TITLE
Audio not working for me

### ISSUE THREAD

**Issue by LgkingDev** [ACCBDD/simplevoicechat-radio#5]
I was trying to communicate with my friend on the radio but apparently i can hear him, but he can't hear me. we made sure we were on the same frequency and we 
were. Don't know if this is my side of the issue or the mods side.

**Comment by ACCBDD** [comment]
Thank you for submitting a report! Could you give me a list of mods you are using as well as their versions, as well as steps to reproduce this? (e.g. what frequency, who is hosting the server and how, whether you are both transmitting at the same time, whether you are on push to talk or voice activation, etc.)
