### ISSUE TITLE
Players that die with a radio equipped in a curio slot can still hear other people talking through the radio

### ISSUE THREAD

**Issue by I-Nocturne-I** [ACCBDD/simplevoicechat-radio#6]
The problem fixes itself when the player picks up their radio again but if they don't they can hear what other players are saying despite not having a radio

**Comment by ACCBDD** [comment]
After further testing this was a general bug where players weren't removed from frequencies in general when they died - this has been fixed in version 1.4.0.2, which is currently waiting for approval on CurseForge. Thank you for reporting this bug!
