### ISSUE TITLE
Player rejoin causes radio 'catch up'

### ISSUE THREAD

**Issue by I-Nocturne-I** [ACCBDD/simplevoicechat-radio#7]
If there are 3 players in a world and 2 of them are talking through a radio and the third person who isn't leaves the session and rejoins they'll hear everything that has been said through the radio from the point at which they left up until they rejoined.

I have a video of what it looks like although github won't let me post it here

**Comment by ACCBDD** [comment]
Thanks for the bug report! You can try sending the video to me at willinghamnottell@gmail.com or on discord at @willnottell

I'm not really sure what could be causing this but I'll try and do some testing to see if I can narrow it down in the meantime.

**Comment by I-Nocturne-I** [comment]
> Thanks for the bug report! You can try sending the video to me at [willinghamnottell@gmail.com](mailto:willinghamnottell@gmail.com) or on discord at @WillNottell
> 
> I'm not really sure what could be causing this but I'll try and do some testing to see if I can narrow it down in the meantime.

I sent the video to your gmail, I've only experienced it once which was 2 months ago but i don't think any of the new updates have fixed it
